using CloudSync.Exceptions.Business;
using CloudSync.Modules.UserManagement.Services.Interfaces;
using Google.Apis.Auth;
using Shared.Requests.UserManagement;

namespace CloudSync.Modules.UserManagement.Services;

public class GoogleTokenValidator(IConfiguration configuration, ILogger<GoogleTokenValidator> logger) : IGoogleTokenValidator
{
    private readonly IConfigurationSection _jwtSettings = configuration.GetSection("JWT");
    
    // Accepts an ID token generated by the frontend login process when a client successfully logins in with their
    // Google account. This tests the ID token against the Google Auth API and returns data about a user's Google account.
    // Returned data includes the Full Name, First and Last Name, Email, Subject (Google User ID string), the time the
    // token was issued at, time before expiration, and information about the Audience, Issuer, and Authorized party.
    public async Task<GoogleJsonWebSignature.Payload> ValidateAsync(GoogleLoginRequest request)
    {
        try
        {
            var audience = _jwtSettings["Audience"];
            logger.LogInformation("Validating Google ID token with audience: {Audience}", audience);
            
            var settings = new GoogleJsonWebSignature.ValidationSettings
            {
                Audience = [audience],
                IssuedAtClockTolerance = TimeSpan.FromMinutes(5),
                ExpirationTimeClockTolerance = TimeSpan.FromMinutes(5)
            };

            var payload = await GoogleJsonWebSignature.ValidateAsync(request.IdToken, settings);
            
            logger.LogInformation("Token validated successfully for user: {Email}", payload.Email);
            return payload;
        }
        catch (InvalidJwtException e) when (e.Message.Contains("expired"))
        {
            logger.LogWarning("Google ID token has expired: {Message}", e.Message);
            throw new AuthenticationException("Google ID token has expired.");
        }
        catch (InvalidJwtException e)
        {
            logger.LogError(e, "Invalid Google ID token. Error: {Message}", e.Message);
            throw new AuthenticationException($"Invalid Google id token: {e.Message}");
        }
        catch (Exception e)
        {
            logger.LogError(e, "Unexpected error validating Google token");
            throw new AuthenticationException($"Token validation failed: {e.Message}");
        }
    }
}